# Generated by Django 6.0.5 on 2026-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
            ],
        ),
        migrations.AddField(
            model_name='departmentannouncement',
            name='category',
            field=models.CharField(choices=[('activity', '學生活動'), ('admin', '校務行政'), ('admission', '升學資訊'), ('notice', '系上通知'), ('honor', '榮譽榜')], default='notice', max_length=20, verbose_name='分類'),
        ),
        migrations.AddField(
            model_name='departmentannouncement',
            name='tags',
            field=models.ManyToManyField(blank=True, to='teams.tag', verbose_name='標籤'),
        ),
    ]
